"""Initial Migration

Revision ID: 077bdc521a53
Revises: 028d4502a400
Create Date: 2019-10-24 11:47:25.168626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077bdc521a53'
down_revision = '028d4502a400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('description', sa.String(length=1000), nullable=True))
    op.drop_column('comments', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('comments', 'description')
    # ### end Alembic commands ###
